version: "3.9"
services:
  bioc:
    container_name: bioc-ess
    image: "nturaga/bioconductor_ess:latest"
    volumes:
      - ${HOME}/R/bioconductor_docker/3.15:/usr/local/lib/R/host-site-library
      - .:/root/

